#!/usr/bin/env bash
link="https://source.unsplash.com/random/"

#environment variables
: "${LUVWALL_CONFIG:=${XDG_CONFIG_HOME:-$HOME/.config}/luvwall.conf}"

[ -f "$LUVWALL_CONFIG" ] && . "$LUVWALL_CONFIG"

: "${wallpaper_setter:=xwallpaper --zoom}"
: "${wall_save_path:=${HOME}/Pictures/wallpaper${RANDOM}.jpg}"
: "${useragent:='Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:100.0) Gecko/20100101 Firefox/100.0'}"
: "${cachedir:=/tmp/livewall}"

[ -d "${cachedir}" ] || mkdir -p "${cachedir}"

wallpaper="${cachedir}/wallpaper.jpg"

die() {
    printf "ERR: %s\n" "$1" >&2
    exit 1
}

wallpaper_prog_cmd() {
    $wallpaper_setter "$wallpaper"
}

save_cmd(){
    cp -i "${wallpaper}" "${wall_save_path}"
}

# reddit {{{
reddit(){
timeout=60
sort=$2
top_time=$3
[ -z "$sort" ] && sort="hot"
[ -z "$top_time" ] && top_time=""

if [ -n "$1" ]; then
    sub=$1
else
    if [ ! -f "${confdir}/subreddits" ]; then
        echo "Please install the subreddits file in ${confdir}"
        exit 2
    fi
    readarray subreddits < "${confdir}/subreddits"
    a=${#subreddits[@]}
    b=$((RANDOM % a))
    sub=${subreddits[$b]}
    sub="$(echo -e "${sub}" | tr -d '[:space:]')"
fi

url="https://www.reddit.com/r/$sub/$sort/.json?raw_json=1&t=$top_time"
content=$(wget -T $timeout -U "$useragent" -q -O - $url)
urls=$(echo -n "$content"| jq -r '.data.children[]|select(.data.post_hint|test("image")?) | .data.preview.images[0].source.url')
names=$(echo -n "$content"| jq -r '.data.children[]|select(.data.post_hint|test("image")?) | .data.title')
ids=$(echo -n "$content"| jq -r '.data.children[]|select(.data.post_hint|test("image")?) | .data.id')
arrURLS=($urls)
arrNAMES=($names)
arrIDS=($ids)
wait # prevent spawning too many processes
size=${#arrURLS[@]}
if [ $size -eq 0 ]; then
    printf '%s\n' "The current subreddit is not valid."
    exit 1
fi
idx=$((RANDOM % size))
target_url=${arrURLS[$idx]}
target_name=${arrNAMES[$idx]}
target_id=${arrIDS[$idx]}
pre_ext=$(echo -n "${target_url##*.}") #|cut -d '?' -f 1)
ext=${pre_ext%?*}
newname=$(echo $target_name | sed "s/^\///;s/\// /g")_"$subreddit"_$target_id.$ext
wget -T $timeout -U "$useragent" --no-check-certificate -q -P down -O "${wallpaper}" $target_url &>/dev/null
}
# }}}
unsplash() {
    local search="${search// /_}"
    if [ -n "$height" ] || [ -n "$width" ]; then
        link="${link}${width}x${height}";
    else
        link="${link}1920x1080";
    fi
    
    [ -n "$search" ] && link="${link}/?${search}"
    wget -q -O "${wallpaper}" $link
}

# devian art {{{
deviantart(){
    [ -z "$devianart_client_id" ] && { devianart_client_id=16531; devianart_client_secret=68c00f3d0ceab95b0fac638b33a3368e; }
    payload="grant_type=client_credentials&client_id=${devianart_client_id}&client_secret=${devianart_client_secret}"
    access_token=$(curl --silent -d $payload https://www.deviantart.com/oauth2/token | jq -r '.access_token')
    if [ -n "$1" ]; then
        artist=$1
        url="https://www.deviantart.com/api/v1/oauth2/gallery/?username=${artist}&mode=popular&limit=24"
    elif [ -n "$search" ]; then
        [[ "$search" =~ ^(tag:)(.*)$ ]] && tag=${BASH_REMATCH[2]}
        if [ ! -z $tag ]; then
            url="https://www.deviantart.com/api/v1/oauth2/browse/tags?tag=$tag&offset=${RANDOM:0:2}&limit=24"
        else
            url="https://www.deviantart.com/api/v1/oauth2/browse/popular?q=$search&limit=24&timerange=1month"
        fi
    else
        #url="https://www.deviantart.com/api/v1/oauth2/browse/hot?limit=24&offset=${offset}"
        topics=( "adoptables" "artisan-crafts" "anthro" "comics" 
          "drawings-and-paintings" "fan-art" "poetry" "stock-images" "sculpture"
          "science-fiction" "traditional-art" "street-photography" "street-art" 
          "pixel-art" "wallpaper" "digital-art" "photo-manipulation" "science-fiction" "fractal"
          "game-art" "fantasy" "3d" "drawings-and-paintings" "game-art" )
        rand=$((RANDOM % ${#topics[@]}))
        url="https://www.deviantart.com/api/v1/oauth2/browse/topic?limit=24&topic=${topics[$rand]}"
    fi
    content=$(curl --silent -H "Authorization: Bearer ${access_token}" \
      -H "Accept: application/json" -H "Content-Type: application/json" $url)
    urls=$(echo -n $content | jq -r '.results[].content.src')
    arrURLS=($urls)
    size=${#arrURLS[@]}
    idx=$((RANDOM % size))
    target_url=${arrURLS[$idx]}
    wget --no-check-certificate -q -P down -O ${wallpaper} $target_url &>/dev/null
}
# }}}

nasa_image() {
    [ -z "$nasa_api" ] && nasa_api=DEMO_KEY
    wget -T 10 -q $(curl -sf "https://api.nasa.gov/planetary/apod?api_key=$nasa_api" \
      |jq -r ".url") -O $wallpaper
}

wallhaven() {
    total_pages=$(curl -s -G "https://wallhaven.cc/api/v1/search" \
      -d "q=$1&atleast=1920x1080&ratios=16x9" | jq '.meta.last_page')
    random_page=$(shuf -i 1-$total_pages -n 1)
    wget -T 10 -q $(curl -s -G "https://wallhaven.cc/api/v1/search" \
                    -d "q=$1&atleast=1920x1080&ratios=16x9&page=$random_page" \
                    | jq -r '.data[].path' | shuf -n 1) -O $wallpaper
}

pixabay() {
    #api limited to 500 images per search
    total_images=$(curl -s -G "https://pixabay.com/api/?key="$pixabay_api"&q=$1&image_type=photo" \
     | jq -r '.totalHits')
    random_page=$((total_images / 20))
    [ $total_images -lt 21 ] && random_page=1
    wget -q $(curl -s -G "https://pixabay.com/api/?key="$pixabay_api"&q=$1&image_type=photo&page=$random_page" \
      | jq -r '.hits[].largeImageURL' | shuf -n 1) -O $wallpaper
}

pexels() {
    total_results="$(curl --user-agent $useragent -s -H "Authorization: $pexels_api" \
      "https://api.pexels.com/v1/search?query=$1&orientation=landscape" | jq '.total_results')"
    total_pages=$((total_results / 15))
    random_page=$(shuf -i 1-$total_pages -n 1)
    wget --show-progress -q -U $useragent "$(curl --user-agent $useragent -s -H "Authorization: $pexels_api" \
    "https://api.pexels.com/v1/search?query=$1&page=$random_page&orientation=landscape" \
    | jq -r '.photos[].src.large' | shuf -n 1)" -O $wallpaper
}

fijo() {
  $wallpaper_setter "$(cat "$HOME"/.local/share/fondo.txt)"
}

bing() {
#  random=$(shuf -i 0-50 -n 1)
  url="$(curl -s "https://www.bing.com/HPImageArchive.aspx?format=js&idx=0&n=9&mkt=en-US" \
    | jq -r '.images[].url' | shuf -n 1)"
  wget -q "https://www.bing.com$url" \
    -O $wallpaper
}

# usage help {{{
usage(){
    echo "Usage: ${0##*/} [-s | --search <string>]
    -h  | --height <height>
    -w  | --width <width>
    -l  | --link <source>
    -p  | --termcolor
    -L  | --lightwal
    -d  | --directory </path/to/dir>
    -e  | --established
    -a  | --artist <deviant artist>
    -B  | --bing
    -n  | --nasa
    -pb | --pixabay <search>
    -px | --pexels <search>
    -r  | --subreddit <subreddit>
    -wh | --wallhaven <search>
    -S  | --save <Save current image to directory>
    "
    exit 2
}
#}}}

# type check {{{
type_check() {
    mime_types=("image/jpeg" "image/png" "image/bmp" "image/gif" "image/heic")
    isType=false
    
    for requiredType in "${mime_types[@]}"; do
        imageType=$(file -b --mime-type ${wallpaper})
        if [ "$requiredType" = "$imageType" ]; then
            isType=true; break
        fi
    done
    
    if [ $isType = false ]; then
        printf '%s\n' "Downloaded file is not an image!"
        exit 1
    fi
}
# }}}

select_local_random_wallpaper () {
    wallpaper=$(find $dir -type f \( -iname "*.jpg" -o -iname "*.jpeg" -o -iname "*.png" \
      -o -iname "*.gif" \) -print | shuf -n 1)
}

pywal_cmd() {
     if [ -n "$pywall" ]; then
       wal -c; wal -i "${wallpaper}" -n -q $light
       [ "$TERM" = alacritty ] && alacritty_change
     fi
}

PARSED_ARGUMENTS=$(getopt -a -n $0 -o h:w:s:l:px:wh:f:r:pb:a:d:peBnLS \
  --long search:,height:,pexels:,width:,bing,pixabay:,wallhaven:,artist:, \
  subreddit:,established,directory:,termcolor:,nasa,lighwal:,save -- "$@")

VALID_ARGUMENTS=$?
if [ "$VALID_ARGUMENTS" != "0" ]; then
    usage; exit
fi
while :; do
    case "${1}" in
        -s | --search)    search=${2} ; shift 2 ;;
        -S | --save)    save_cmd; exit ;;
        -h | --height)    height=${2} ; shift 2 ;;
        -w | --width)     width=${2} ; shift 2 ;;
        -l | --link)      link=link ; search=${2} ; shift 2 ;;
        -r | --subreddit) sub=${2} ; shift 2 ;;
        -a | --artist) artist=${2} ; shift 2 ;;
        -L | --lightwal)  pywall=true; light='-l' ; shift ;;
        -p | --termcolor) pywall=true ; shift ;;
        -d | --directory) dir=${2};link=null ; shift 2 ;;
        -n | --nasa) link=nasa ; shift ;;
        -e | --established) fijo ; exit;;
        -B | --bing) link=bing ; shift;;
        -wh | --wallhaven) search=${2}; link=wallhaven ; shift 2;;
        -pb | --pixabay) search=${2}; link=pixabay; shift 2;;
        -px | --pexels) search=${2}; link=pexels; shift 2;;
        -- | '') shift; break ;;
        *) usage ;;
    esac
done

case $link in
  null) select_local_random_wallpaper;;
  reddit)reddit "$sub";;
  devianart) devianart "$artist";;
  wallhaven) wallhaven "$search";;
  pexels) pexels "$search";;
  pixabay) pixabay "$search";;
  bing) bing;;
  nasa)nasa_image;;
  link) wget -U "useragent" -q "$search" -O $wallpaper;;
  *)unsplash;;
esac

type_check
wallpaper_prog_cmd
pywal_cmd

# vim:foldmethod=marker
