#!/usr/bin/env bash

#environment variables
: "${LUVWALL_CONFIG:=${XDG_CONFIG_HOME:-$HOME/.config}/luvwall.conf}"
[ -f "$LUVWALL_CONFIG" ] && . "$LUVWALL_CONFIG"

: "${wallpaper_setter:=xwallpaper --zoom}"
: "${wall_save_path:=${XDG_PICTURES_DIR:=$HOME/Pictures}/wallpaper${RANDOM}.jpg}"
: "${useragent:='Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:100.0) Gecko/20100101 Firefox/100.0'}"
: "${cachedir:=/tmp/livewall}"

timeout=60
confdir=${XDG_CONFIG_HOME:-$HOME/.config}

[ -d "${cachedir}" ] || mkdir -p "${cachedir}"

wallpaper="${cachedir}/wallpaper.jpg"

die() {
    printf '\033[1;31m%s \033[0m\n' "ERR: $1" >&2
    exit 1
}

wallpaper_prog_cmd() {
    $wallpaper_setter "$wallpaper"
}

save_cmd(){
    cp -i "${wallpaper}" "${wall_save_path}" \
      && notify-send -u low -t 2000 "copied to ${wall_save_path}" 2>/dev/null \
      || notify-send -u critical -t 4000 "not copied" 2>/dev/null
}

# reddit {{{
reddit(){
  sort=$2
  top_time=$3
  [ -z "$sort" ] && sort="hot"
  [ -z "$top_time" ] && top_time=""
  
  if [ -n "$1" ]; then
      sub=$1
  else
      if [ ! -f "${confdir}/subreddits" ]; then
          die "Please install the subreddits file in ${confdir}"
      fi
      readarray subreddits < "${confdir}/subreddits"
      a=${#subreddits[@]}
      b=$((RANDOM % a))
      sub=${subreddits[$b]}
      sub="$(echo -e "${sub}" | tr -d '[:space:]')"
  fi
  
  url="https://www.reddit.com/r/$sub/$sort/.json?raw_json=1&t=$top_time"
  content=$(wget -T $timeout -U "$useragent" -q -O - $url)
  urls=$(echo -n "$content"| jq -r '.data.children[]|select(.data.post_hint|test("image")?) | .data.preview.images[0].source.url')
  names=$(echo -n "$content"| jq -r '.data.children[]|select(.data.post_hint|test("image")?) | .data.title')
  ids=$(echo -n "$content"| jq -r '.data.children[]|select(.data.post_hint|test("image")?) | .data.id')
  arrURLS=($urls)
  arrNAMES=($names)
  arrIDS=($ids)
  wait # prevent spawning too many processes
  size=${#arrURLS[@]}
  [ "$size" -eq 0 ] && die "The current subreddit is not valid."
  idx=$((RANDOM % size))
  target_url=${arrURLS[$idx]}
  target_name=${arrNAMES[$idx]}
  target_id=${arrIDS[$idx]}
  pre_ext=$(echo -n "${target_url##*.}") #|cut -d '?' -f 1)
  ext=${pre_ext%?*}
  newname=$(echo $target_name | sed "s/^\///;s/\// /g")_"$subreddit"_$target_id.$ext
  wget -T $timeout -U "$useragent" --no-check-certificate -q -P down -O "${wallpaper}" $target_url &>/dev/null
}
# }}}
unsplash() {
  link="https://source.unsplash.com/random/"
    local search="${search// /_}"
    if [ -n "$height" ] || [ -n "$width" ]; then
        link="${link}${width}x${height}"
    else
        link="${link}1920x1080"
    fi

    [ -n "$search" ] && link="${link}/?${search}"
    wget -q -O "${wallpaper}" $link
}

# deviant art {{{
deviantart(){
    : "${devianart_client_secret:=68c00f3d0ceab95b0fac638b33a3368e}"
    payload="grant_type=client_credentials&client_id=${devianart_client_id:=16531}&client_secret=${devianart_client_secret}"
    access_token=$(curl --silent -d $payload https://www.deviantart.com/oauth2/token | jq -r '.access_token')
    
    if [ -n "$1" ]; then
        artist=$1
        url="https://www.deviantart.com/api/v1/oauth2/gallery/?username=${artist}&mode=popular&limit=24"
    elif [ -n "$search" ]; then
        [[ "$search" =~ ^(tag:)(.*)$ ]] && tag=${BASH_REMATCH[2]}
        if [ ! -z $tag ]; then
            url="https://www.deviantart.com/api/v1/oauth2/browse/tags?tag=$tag&offset=${RANDOM:0:2}&limit=24"
        else
            url="https://www.deviantart.com/api/v1/oauth2/browse/popular?q=$search&limit=24&timerange=1month"
        fi
    else
        #url="https://www.deviantart.com/api/v1/oauth2/browse/hot?limit=24&offset=${offset}"
        topics=( "adoptables" "artisan-crafts" "anthro" "comics"
          "drawings-and-paintings" "fan-art" "poetry" "stock-images" "sculpture"
          "science-fiction" "traditional-art" "street-photography" "street-art"
          "pixel-art" "wallpaper" "digital-art" "photo-manipulation" "science-fiction" "fractal"
          "game-art" "fantasy" "3d" "drawings-and-paintings" "game-art" )
        rand=$((RANDOM % ${#topics[@]}))
        url="https://www.deviantart.com/api/v1/oauth2/browse/topic?limit=24&topic=${topics[$rand]}"
    fi
   
    content=$(curl --silent -H "Authorization: Bearer ${access_token}" \
      -H "Accept: application/json" -H "Content-Type: application/json" $url)
    urls=$(echo -n $content | jq -r '.results[].content.src')
    arrURLS=($urls)
    size=${#arrURLS[@]}
    idx=$((RANDOM % size))
    target_url=${arrURLS[$idx]}
    wget --no-check-certificate -q -P down -O ${wallpaper} $target_url &>/dev/null
}
# }}}

nasa_image() {
    [ "$link" = "nasa_random" ] \
      && day=$(shuf -n1 -i $(date -d "${nasa_start_date:=2000-01-01}" '+%s')-$(date '+%s')\
      | xargs -I{} date -d '@{}' '+%Y-%m-%d') && echo "image of the day of $day"
    wget -T $timeout -q $(curl -sf -G "https://api.nasa.gov/planetary/apod?api_key=${nasa_api:-DEMO_KEY}" -d "date=$day" \
      |jq -r ".url") -O $wallpaper 2>/dev/null
}

wallhaven() {
    total_pages=$(curl -s -G "https://wallhaven.cc/api/v1/search" \
      -d "q=$1&atleast=1920x1080&ratios=16x9" | jq '.meta.last_page')
    random_page=$(shuf -i 1-$total_pages -n 1)
    wget -T $timeout -q $(curl -s -G "https://wallhaven.cc/api/v1/search" \
                    -d "q=$1&atleast=1920x1080&ratios=16x9&page=$random_page" \
                    | jq -r '.data[].path' | shuf -n 1) -O $wallpaper
}

pixabay() {
    #api limited to 500 images per search
    total_images=$(curl -s -G "https://pixabay.com/api/?key="$pixabay_api"&q=$1&image_type=photo" \
     | jq -r '.totalHits')
    random_page=$((total_images / 20))
    [ $total_images -lt 21 ] && random_page=1
    wget -q $(curl -s -G "https://pixabay.com/api/?key="$pixabay_api"&q=$1&image_type=photo&page=$random_page" \
      | jq -r '.hits[].largeImageURL' | shuf -n 1) -O $wallpaper
}

pexels() {
    total_results="$(curl --user-agent $useragent -s -H "Authorization: $pexels_api" \
      "https://api.pexels.com/v1/search?query=$1&orientation=landscape" | jq '.total_results')"
    total_pages=$((total_results / 15))
    random_page=$(shuf -i 1-$total_pages -n 1)
    wget --show-progress -q -U $useragent "$(curl --user-agent $useragent -s -H "Authorization: $pexels_api" \
    "https://api.pexels.com/v1/search?query=$1&page=$random_page&orientation=landscape" \
    | jq -r '.photos[].src.large' | shuf -n 1)" -O $wallpaper
}

fijo() {
  $wallpaper_setter "${XDG_CACHE_HOME:=$HOME/.cache}/fondo"
}

bing() {
  url="$(curl -s "https://www.bing.com/HPImageArchive.aspx?format=js&idx=0&n=${bing_day:=9}&mkt=en-US" \
    | jq -r '.images[].url' | shuf -n 1)"
  wget -q "https://www.bing.com$url" \
    -O $wallpaper
}

# usage help {{{
usage(){
    echo "Usage: ${0##*/}
    [-s <string>] search unsplash
    [-H <height>]
    [-W <width>]
    [-l <link>] set wallpaper from link
    [-P]  pywall
    [-L]  pywall light color scheme
    [-a <artist>] deviantart
    [-b]  bing
    [-n]  nasa image of the day
    [-N]  nasa random image
    [-p <search>] pixabay
    [-x <search>] pexels
    [-r <subreddit>] reddit
    [-w <search>] wallhaven
    [-S]  save current image
    [-e]  restore saved wallpaper
    [-d </path/to/dir>] random image from directory"
    exit 2
}
#}}}

# type check {{{
type_check() {
    mime_types="image/jpeg image/png image/bmp image/gif image/heic"

    imageType=$(file -b --mime-type $wallpaper)
    for requiredType in $mime_types; do
        if [ "$requiredType" = "$imageType" ]; then
            isType=true; break
        fi
    done

    [ "$isType" ] || die "Downloaded file is not an image!"
}
# }}}

select_local_random_wallpaper () {
    wallpaper=$(find $dir -type f \( -iname "*.jpg" -o -iname "*.jpeg" -o -iname "*.png" \
      -o -iname "*.gif" \) -print | shuf -n 1)
}

pywal_cmd() {
     if [ -n "$pywall" ]; then
       wal -c; wal -i "${wallpaper}" -n -q $light
       [ "$TERM" = alacritty ] && alacritty_change
     fi
}

while getopts 'eSbnNs:d:w:p:x:' o; do
    case "$o" in
        e) fijo ; exit;;
        S) save_cmd; exit ;;
        s) search=$OPTARG ;;
        H) height=$OPTARG ;;
        W) width=$OPTARG ;;
        l) link=link ; search=$OPTARG ;;
        r) sub=$OPTARG; link=reddit ;;
        a) artist=$OPTARG; link=deviantart ;;
        L) pywall=true; light='-l' ;;
        P) pywall=true ;;
        d) dir=$OPTARG;link=null ; ;;
        n) link=nasa  ;;
        N) link=nasa_random ;;
        b) link=bing ;;
        w) search=$OPTARG; link=wallhaven ;;
        p) search=$OPTARG; link=pixabay;;
        x) search=$OPTARG; link=pexels;;
        *) usage ;;
    esac
done

shift $((OPTIND - 1))

case $link in
  null) select_local_random_wallpaper;;
  reddit) reddit "$sub";;
  deviantart) deviantart "$artist";;
  wallhaven) wallhaven "$search";;
  pexels) pexels "$search";;
  pixabay) pixabay "$search";;
  bing) bing;;
  nasa*) nasa_image;;
  link) wget -U "$useragent" -q "$search" -O $wallpaper;;
  *)unsplash;;
esac

type_check
wallpaper_prog_cmd
pywal_cmd

# vim:foldmethod=marker
